apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${svc_name}-${version}
  namespace: ${svc_name}
  labels:
    app: ${svc_name}
    version: ${version} 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${svc_name}
      version: ${version}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4202"
        prometheus.io/path: "/metrics"
      labels:
        app: ${svc_name}
        version: ${version}
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
        #whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: ${svc_name}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 60
            preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType
                operator: In
                values:
                - SPOT
          - weight: 40
            preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType
                operator: In
                values:
                - "ON_DEMAND"      
      serviceAccountName: ${svc_name}
      containers:
      #- name: utils
      #  image: 925332100543.dkr.ecr.ap-south-1.amazonaws.com/toughiq/network-multitool:latest
      #  imagePullPolicy: Always
      - name: ${svc_name}
        image: 925332100543.dkr.ecr.ap-south-1.amazonaws.com/${svc_name}:${image_tag}
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: ${node_env}
        ports:
        - containerPort: 3000
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: ${service_api}health-check
            port: 3000
        resources:
            limits:
              memory: ${memory_limit}
              cpu: ${cpu_limit}
            requests:
              memory: ${memory_request}
              cpu: ${cpu_request}
      imagePullSecrets:
      - name: ecr-login